// ═══════════════════════════════════════════════
//  JSON ATLAS — Type Inference & Code Generation
// ═══════════════════════════════════════════════

let currentTab = 'ts';
let generatedCode = { ts: '', py: '', go: '' };

// ─── ENTRY POINT ───
function generate() {
    const raw = document.getElementById('json-input').value;
    const errEl = document.getElementById('error-msg');

    let data;
    try {
        data = JSON.parse(raw);
        errEl.style.display = 'none';
    } catch (e) {
        errEl.textContent = '✕ ' + e.message;
        errEl.style.display = 'block';
        return;
    }

    updateStats(raw);

    // Collect all named types
    const typeRegistry = [];
    inferType(data, 'Root', typeRegistry);

    generatedCode.ts = emitTypeScript(typeRegistry);
    generatedCode.py = emitPython(typeRegistry);
    generatedCode.go = emitGo(typeRegistry);

    document.getElementById('out-ts').textContent = generatedCode.ts;
    document.getElementById('out-py').textContent = generatedCode.py;
    document.getElementById('out-go').textContent = generatedCode.go;
}

// ═══════════════════════════════════════════════
//  TYPE INFERENCE ENGINE
// ═══════════════════════════════════════════════

function inferType(value, suggestedName, registry) {
    if (value === null) return { kind: 'null' };
    if (typeof value === 'boolean') return { kind: 'bool' };
    if (typeof value === 'string') return { kind: 'string' };
    if (typeof value === 'number') {
        return { kind: Number.isInteger(value) ? 'int' : 'float' };
    }

    if (Array.isArray(value)) {
        if (value.length === 0) return { kind: 'array', element: { kind: 'unknown' } };

        // Infer element type from first element; use singular name
        const elemName = singularize(suggestedName);
        const elemType = inferType(value[0], elemName, registry);

        // If there are multiple objects, merge their keys for a more complete type
        if (elemType.kind === 'ref' && value.length > 1) {
            const existing = registry.find(t => t.name === elemType.ref);
            if (existing) {
                for (let i = 1; i < value.length; i++) {
                    if (value[i] !== null && typeof value[i] === 'object' && !Array.isArray(value[i])) {
                        mergeObjectFields(existing, value[i], registry);
                    }
                }
            }
        }

        return { kind: 'array', element: elemType };
    }

    if (typeof value === 'object') {
        const typeName = pascalCase(suggestedName);
        const fields = [];

        for (const key of Object.keys(value)) {
            const childName = pascalCase(key);
            const childType = inferType(value[key], childName, registry);
            fields.push({ key: key, type: childType });
        }

        const typeEntry = { name: typeName, fields: fields };
        registry.push(typeEntry);
        return { kind: 'ref', ref: typeName };
    }

    return { kind: 'unknown' };
}

function mergeObjectFields(typeEntry, obj, registry) {
    for (const key of Object.keys(obj)) {
        const exists = typeEntry.fields.find(f => f.key === key);
        if (!exists) {
            const childName = pascalCase(key);
            const childType = inferType(obj[key], childName, registry);
            typeEntry.fields.push({ key: key, type: childType, optional: true });
        }
    }
}

// ═══════════════════════════════════════════════
//  EMITTERS
// ═══════════════════════════════════════════════

// ── TypeScript ──
function emitTypeScript(registry) {
    const lines = ['// Generated by JSON Atlas', '// https://priyamsameer95-sys.github.io/2026-08-22-json-atlas/', ''];

    for (const type of registry) {
        lines.push(`interface ${type.name} {`);
        for (const field of type.fields) {
            const opt = field.optional ? '?' : '';
            const nullable = field.type.kind === 'null';
            lines.push(`  ${safeKey(field.key)}${opt}: ${tsType(field.type)};`);
        }
        lines.push('}');
        lines.push('');
    }

    return lines.join('\n');
}

function tsType(t) {
    if (t.kind === 'string') return 'string';
    if (t.kind === 'int' || t.kind === 'float') return 'number';
    if (t.kind === 'bool') return 'boolean';
    if (t.kind === 'null') return 'null';
    if (t.kind === 'unknown') return 'unknown';
    if (t.kind === 'ref') return t.ref;
    if (t.kind === 'array') return `${tsType(t.element)}[]`;
    return 'unknown';
}

// ── Python ──
function emitPython(registry) {
    const lines = [
        '# Generated by JSON Atlas',
        '# https://priyamsameer95-sys.github.io/2026-08-22-json-atlas/',
        '',
        'from __future__ import annotations',
        'from dataclasses import dataclass',
        'from typing import Optional',
        ''
    ];

    // Emit in reverse so dependencies come first
    const reversed = [...registry].reverse();

    for (const type of reversed) {
        lines.push('@dataclass');
        lines.push(`class ${type.name}:`);
        if (type.fields.length === 0) {
            lines.push('    pass');
        } else {
            for (const field of type.fields) {
                const pyT = pyType(field.type);
                const annotation = field.optional ? `Optional[${pyT}]` : (field.type.kind === 'null' ? `Optional[${pyT}]` : pyT);
                lines.push(`    ${safeSnake(field.key)}: ${annotation}`);
            }
        }
        lines.push('');
    }

    return lines.join('\n');
}

function pyType(t) {
    if (t.kind === 'string') return 'str';
    if (t.kind === 'int') return 'int';
    if (t.kind === 'float') return 'float';
    if (t.kind === 'bool') return 'bool';
    if (t.kind === 'null') return 'None';
    if (t.kind === 'unknown') return 'object';
    if (t.kind === 'ref') return t.ref;
    if (t.kind === 'array') return `list[${pyType(t.element)}]`;
    return 'object';
}

// ── Go ──
function emitGo(registry) {
    const lines = [
        '// Generated by JSON Atlas',
        '// https://priyamsameer95-sys.github.io/2026-08-22-json-atlas/',
        '',
        'package main',
        ''
    ];

    // Emit in reverse so dependencies come first
    const reversed = [...registry].reverse();

    for (const type of reversed) {
        lines.push(`type ${type.name} struct {`);
        for (const field of type.fields) {
            const goFieldName = pascalCase(field.key);
            const goT = goType(field.type, field.type.kind === 'null');
            const tag = '`json:"' + field.key + '"`';
            // Align with padding
            const padName = goFieldName.padEnd(16);
            const padType = goT.padEnd(16);
            lines.push(`\t${padName}${padType}${tag}`);
        }
        lines.push('}');
        lines.push('');
    }

    return lines.join('\n');
}

function goType(t, nullable) {
    const ptr = nullable ? '*' : '';
    if (t.kind === 'string') return ptr + 'string';
    if (t.kind === 'int') return ptr + 'int';
    if (t.kind === 'float') return ptr + 'float64';
    if (t.kind === 'bool') return ptr + 'bool';
    if (t.kind === 'null') return 'interface{}';
    if (t.kind === 'unknown') return 'interface{}';
    if (t.kind === 'ref') return ptr + t.ref;
    if (t.kind === 'array') return '[]' + goType(t.element, false);
    return 'interface{}';
}

// ═══════════════════════════════════════════════
//  UI ACTIONS
// ═══════════════════════════════════════════════

function switchTab(tab, btn) {
    currentTab = tab;
    document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
    btn.classList.add('active');
    document.querySelectorAll('.output-panel').forEach(p => p.classList.remove('active'));
    document.getElementById('panel-' + tab).classList.add('active');
    // Reset copy button
    const copyBtn = document.getElementById('copy-btn');
    copyBtn.textContent = 'Copy';
    copyBtn.classList.remove('copied');
}

function copyOutput() {
    const code = generatedCode[currentTab];
    if (!code) return;
    navigator.clipboard.writeText(code).then(() => {
        const btn = document.getElementById('copy-btn');
        btn.textContent = 'Copied!';
        btn.classList.add('copied');
        setTimeout(() => { btn.textContent = 'Copy'; btn.classList.remove('copied'); }, 1500);
    }).catch(() => {});
}

function formatJSON() {
    const el = document.getElementById('json-input');
    try { el.value = JSON.stringify(JSON.parse(el.value), null, 2); liveValidate(); } catch (e) {}
}

function minifyJSON() {
    const el = document.getElementById('json-input');
    try { el.value = JSON.stringify(JSON.parse(el.value)); liveValidate(); } catch (e) {}
}

function loadSample() {
    document.getElementById('json-input').value = JSON.stringify({
        "user": {
            "id": 1042,
            "name": "Jane Doe",
            "email": "jane@example.com",
            "is_active": true,
            "role": null
        },
        "orders": [
            {
                "order_id": "ORD-881",
                "total": 129.99,
                "items": [
                    { "sku": "WDG-01", "name": "Widget Pro", "qty": 2, "price": 49.99 },
                    { "sku": "PLG-07", "name": "Plugin Basic", "qty": 1, "price": 30.01 }
                ],
                "shipped": true
            }
        ],
        "settings": {
            "theme": "dark",
            "notifications": { "email": true, "sms": false, "push": true }
        }
    }, null, 2);
    liveValidate();
    generate();
}

function clearAll() {
    document.getElementById('json-input').value = '';
    document.getElementById('error-msg').style.display = 'none';
    document.getElementById('stat-line').textContent = '';
    document.getElementById('out-ts').textContent = '// Click "Generate Code →" to see TypeScript interfaces';
    document.getElementById('out-py').textContent = '# Click "Generate Code →" to see Python dataclasses';
    document.getElementById('out-go').textContent = '// Click "Generate Code →" to see Go structs';
    generatedCode = { ts: '', py: '', go: '' };
}

function liveValidate() {
    const raw = document.getElementById('json-input').value;
    const errEl = document.getElementById('error-msg');
    if (!raw.trim()) { errEl.style.display = 'none'; return; }
    try { JSON.parse(raw); errEl.style.display = 'none'; } catch (e) {
        errEl.textContent = '✕ ' + e.message;
        errEl.style.display = 'block';
    }
}

function openModal() { document.getElementById('help-modal').style.display = 'flex'; }
function closeModal() { document.getElementById('help-modal').style.display = 'none'; }

// ═══════════════════════════════════════════════
//  UTILITIES
// ═══════════════════════════════════════════════

function updateStats(raw) {
    const bytes = new Blob([raw]).size;
    let size = bytes < 1024 ? bytes + ' B' : (bytes / 1024).toFixed(1) + ' KB';
    const lines = raw.split('\n').length;
    document.getElementById('stat-line').textContent = `${lines} lines · ${size}`;
}

function pascalCase(str) {
    return str
        .replace(/[^a-zA-Z0-9]+/g, ' ')
        .split(' ')
        .filter(Boolean)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join('');
}

function safeKey(key) {
    // If key has special chars, wrap in quotes
    if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) return key;
    return '"' + key + '"';
}

function safeSnake(key) {
    // Convert to snake_case for Python
    let s = key.replace(/[^a-zA-Z0-9]/g, '_').replace(/([A-Z])/g, '_$1').toLowerCase();
    s = s.replace(/^_+/, '').replace(/_+/g, '_');
    if (!s) s = 'field';
    // Avoid Python reserved words
    const reserved = ['class', 'def', 'return', 'import', 'from', 'if', 'else', 'for', 'while', 'try', 'except', 'with', 'as', 'pass', 'type'];
    if (reserved.includes(s)) s = s + '_';
    return s;
}

function singularize(name) {
    // Very basic singularization for type naming
    if (name.endsWith('ies')) return name.slice(0, -3) + 'y';
    if (name.endsWith('ses')) return name.slice(0, -2);
    if (name.endsWith('s') && !name.endsWith('ss')) return name.slice(0, -1);
    return name + 'Item';
}

// ─── INIT ───
window.onload = function () {
    liveValidate();
    generate();
};
